import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { WithDataProvider } from "../providers/asteroid-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/layout.css"></link>
        <link
          rel="stylesheet"
          href="https://nordcdn.net/ds/css/3.1.0/nord.min.css"
        />
      </head>
      <body className={inter.className}>
        <WithDataProvider>
          <div id="layout">
            <header>Placer.ai Asteroids Research Center</header>
            <nav>
              <Link className="nav-item" href="/overview">
                Overview
              </Link>
              <Link className="nav-item" href="/investigate">
                Investigate
              </Link>
            </nav>
            <main>{children}</main>
          </div>
        </WithDataProvider>
      </body>
    </html>
  );
}
